/* The /faq page's built-in fallback questions, now in both site languages.
 * The list previously existed only in Danish inside the page itself, so an
 * English visitor got Danish answers no matter what the toggle said. The KV
 * FAQ (manager-edited) already stores {da,en}; this fallback now matches. */
export const DEFAULT_FAQ_BILINGUAL = [
  { q: { da: "Kan dampvask skade lakken?", en: "Can steam washing damage the paintwork?" },
    a: { da: "Nej – dampvask er faktisk skånsom for lakken end traditionel højtryk- eller tunnelvask. Vi bruger professionel damp ved kontrolleret temperatur og bløde mikrofiberklude. Ingen roterende børster og ingen aggressive kemikalier. Metoden er anbefalet til biler med keramisk coating, poleret lak og sarte overflader.",
      en: "No – steam washing is gentler on paintwork than traditional high-pressure or tunnel washing. We use professional steam at a controlled temperature and soft microfibre cloths. No rotating brushes and no aggressive chemicals. The method is recommended for cars with ceramic coating, polished paint and delicate surfaces." } },
  { q: { da: "Hvor lang tid tager det?", en: "How long does it take?" },
    a: { da: "Det afhænger af bilstørrelse og pakke: Lille bil: 100–120 min · Mellemstor bil: 120–180 min · Stor bil / SUV: 150–200 min · Varebil: 90–180 min. Vi er altid præcise med vores tidsestimater og holder dig opdateret undervejs.",
      en: "It depends on car size and package: Small car: 100–120 min · Medium car: 120–180 min · Large car / SUV: 150–200 min · Van: 90–180 min. We always give accurate time estimates and keep you updated along the way." } },
  { q: { da: "Skal jeg være hjemme?", en: "Do I need to be home?" },
    a: { da: "Ikke nødvendigvis. Mange kunder er på arbejde, mens vi vasker bilen. Det eneste krav er, at bilen er tilgængelig og at der er fri adgang rundt om den. Ring eller skriv til os, så finder vi en løsning der passer dig.",
      en: "Not necessarily. Many customers are at work while we wash the car. The only requirement is that the car is accessible with clear space around it. Call or write to us and we'll find a solution that suits you." } },
  { q: { da: "Vasker I elbiler?", en: "Do you wash electric cars?" },
    a: { da: "Ja, vi vasker alle typer elbiler – Tesla, Polestar, VW ID, Hyundai Ioniq og alle andre mærker. Dampvask er ideelt til elbiler: vi bruger minimalt vand, ingen aggressive kemikalier der kan påvirke tætninger og elektronik, og vi undgår højtryk tæt på batteripakke og ladeporte.",
      en: "Yes, we wash all types of electric cars – Tesla, Polestar, VW ID, Hyundai Ioniq and every other brand. Steam washing is ideal for EVs: minimal water, no aggressive chemicals that could affect seals and electronics, and we avoid high pressure near the battery pack and charging ports." } },
  { q: { da: "Hvad hvis det regner?", en: "What if it rains?" },
    a: { da: "Let regn er sjældent et problem – vi kan vaske under overdækning, i carporte eller i garager. Ved kraftigt regn kontakter vi dig dagen inden og tilbyder at ombooke til nærmeste ledige tid helt uden gebyr.",
      en: "Light rain is rarely a problem – we can wash under cover, in carports or garages. In heavy rain we contact you the day before and offer to rebook to the nearest available time at no charge." } },
  { q: { da: "Hvad koster mobil bilvask?", en: "What does mobile car washing cost?" },
    a: { da: "Prisen afhænger af biltype og pakke: Udvendig vask fra 500 kr · Hel bil (ind & ud) fra 800 kr · Guld pakke (inkl. motorrens + lakforsegling) fra 2.000 kr. Kørsel til din adresse på Sjælland er gratis.",
      en: "The price depends on car type and package: Exterior wash from 500 kr · Full car (inside & out) from 800 kr · Gold package (incl. engine clean + paint sealant) from 2,000 kr. Travel to your address on Zealand is free." } },
  { q: { da: "Kommer I til min adresse?", en: "Do you come to my address?" },
    a: { da: "Ja – det er hele idéen! Vi er 100% mobile og kører ud til dig, uanset om du er hjemme, på arbejdet eller i sommerhuset. Du behøver slet ikke flytte dig. Vi medbringer alt udstyr.",
      en: "Yes – that's the whole idea! We are 100% mobile and drive out to you, whether you're at home, at work or at the summer house. You don't have to move at all. We bring all the equipment." } },
  { q: { da: "Arbejder I i hele Sjælland?", en: "Do you cover all of Zealand?" },
    a: { da: "Ja! Vi dækker hele Sjælland – postnumre 1000–4799 – inkl. Storkøbenhavn, Nordsjælland, Køge, Roskilde, Næstved, Ringsted og omegn. Kørsel er gratis til alle adresser inden for serviceområdet.",
      en: "Yes! We cover all of Zealand – postcodes 1000–4799 – including Greater Copenhagen, North Zealand, Køge, Roskilde, Næstved, Ringsted and surroundings. Travel is free to every address inside the service area." } },
  { q: { da: "Er dampvask sikkert for min bil?", en: "Is steam washing safe for my car?" },
    a: { da: "Ja, dampvask er skånsomt for bilen. Vi bruger professionelle, pH-neutrale produkter og varm damp der løsner snavs uden at ridse lakken. Metoden bruges af professionelle detailere verden over og er anbefalet til biler med keramisk coating og poleret lak.",
      en: "Yes, steam washing is gentle on the car. We use professional, pH-neutral products and hot steam that loosens dirt without scratching the paint. The method is used by professional detailers worldwide and recommended for cars with ceramic coating and polished paint." } },
  { q: { da: "Hvad er inkluderet i Guld pakken?", en: "What is included in the Gold package?" },
    a: { da: "Guld pakken er vores mest komplette behandling og inkluderer alt: Komplet udvendig dampvask · Grundig indvendig rens · Professionel motorrens · Lak- & glansbeskyttelse (lakforsegling) · Interiørbeskyttelse · Dybderens ved uheld. Vores mest populære valg til biler der skal fremstå som nye.",
      en: "The Gold package is our most complete treatment and includes everything: Complete exterior steam wash · Thorough interior clean · Professional engine clean · Paint & gloss protection (sealant) · Interior protection · Deep clean where needed. Our most popular choice for cars that should look like new." } },
  { q: { da: "Kan I vaske leasingbiler?", en: "Do you prepare lease cars?" },
    a: { da: "Ja, vi klargør leasingbiler til aflevering. Vi sørger for at bilen fremstår ren og velholdt – både udvendigt og indvendigt – så du undgår ekstraomkostninger ved aflevering.",
      en: "Yes, we prepare lease cars for return. We make sure the car looks clean and well kept – inside and out – so you avoid extra charges at hand-back." } },
  { q: { da: "Hvad er forskellen på dampvask og almindelig bilvask?", en: "How does steam washing differ from a regular wash?" },
    a: { da: "Traditionel bilvask ridser lakken over tid med børster og aggressive kemikalier. Dampvask bruger varme og tryk til at løsne snavs skånsomt – uden børster, uden aggressive kemikalier og med op til 90% mindre vandforbrug. Resultatet er en dybere rens, bedre glans og ingen mikroridser.",
      en: "Traditional car washing scratches paintwork over time with brushes and harsh chemicals. Steam uses heat and pressure to loosen dirt gently – no brushes, no harsh chemicals, and up to 90% less water. The result is a deeper clean, better gloss and no micro-scratches." } },
  { q: { da: "Skal jeg forberede bilen inden I kommer?", en: "Should I prepare the car before you arrive?" },
    a: { da: "Det er ikke nødvendigt, men du er velkommen til at fjerne løse genstande og personlige ejendele fra kabinen. Sørg blot for at bilen er tilgængelig og at der er fri plads rundt om den. Vi klarer resten!",
      en: "It isn't necessary, but you're welcome to remove loose items and personal belongings from the cabin. Just make sure the car is accessible with clear space around it. We handle the rest!" } },
  { q: { da: "Kan I vaske elbiler og hybridbiler?", en: "Do you wash electric and hybrid cars?" },
    a: { da: "Ja, vi vasker alle typer elbiler og hybridbiler. Dampvask er ideel til elbiler – vi bruger minimalt vand og ingen aggressive kemikalier, der kan påvirke tætninger og elektronik. Vi undgår naturligvis højtryksrenser tæt på batteripakken og ladeporte.",
      en: "Yes, we wash all electric and hybrid cars. Steam is ideal for EVs – minimal water and no aggressive chemicals that could affect seals or electronics. We naturally avoid pressure washing near the battery pack and charging ports." } },
  { q: { da: "Hvad er forskellen på udvendig, indvendig og hel vask?", en: "What's the difference between exterior, interior and full wash?" },
    a: { da: "Udvendig vask dækker karosseri, ruder, fælge og dæk. Indvendig vask dækker sæder, gulvmåtter, instrumentbræt, dørpaneler og ruder indefra. Hel vask er kombinationen af begge og er den mest populære løsning – alt renses i ét besøg.",
      en: "Exterior covers bodywork, windows, wheels and tyres. Interior covers seats, floor mats, dashboard, door panels and inside windows. The full wash combines both and is the most popular option – everything cleaned in one visit." } },
  { q: { da: "Hvad sker der, hvis det regner på min bookingdag?", en: "What happens if it rains on my booking day?" },
    a: { da: "Vi kontakter dig dagen inden og tilbyder enten at fortsætte (let regn er sjældent et problem indendørs eller under overdækning) eller at ombooke til nærmeste ledige tid uden ekstra gebyr. Vi er fleksible og finder altid en løsning.",
      en: "We contact you the day before and offer either to go ahead (light rain is rarely a problem indoors or under cover) or to rebook to the nearest available time at no extra charge. We're flexible and always find a solution." } },
  { q: { da: "Bruger I kemikalier, der kan skade lakken?", en: "Do you use chemicals that can harm the paint?" },
    a: { da: "Nej. Vi bruger miljøvenlige rengøringsmidler, der er testet til brug på biloverflader. Dampvasken kræver desuden langt færre kemikalier end traditionel bilvask – den varme damp opløser snavs og fedt mekanisk uden at angribe lakken.",
      en: "No. We use eco-friendly cleaning products tested for car surfaces. Steam washing also needs far fewer chemicals than a traditional wash – the hot steam dissolves dirt and grease mechanically without attacking the paint." } },
  { q: { da: "Kan I vaske bilen, selvom den er meget beskidt eller fuld af dyrehår?", en: "Can you wash a very dirty car, or one full of pet hair?" },
    a: { da: "Ja. Vi er vant til biler i alle tilstande – fra leasingbiler klar til aflevering til familievogne med sæsoners ophobede snavs og kæledyrhår. Meget kraftig tilsmudsning kan kræve ekstra tid, som vi aftaler med dig på forhånd.",
      en: "Yes. We're used to cars in every condition – from lease cars ready for return to family cars with seasons of built-up dirt and pet hair. Very heavy soiling may take extra time, which we agree with you in advance." } },
  { q: { da: "Tilbyder I erhvervsaftaler til virksomheder med flåder?", en: "Do you offer business agreements for fleets?" },
    a: { da: "Ja, vi laver aftaler med virksomheder, der har behov for regelmæssig vask af firmabiler, varevogne eller hele flåder. Kontakt os på info@elite-vask.dk for et tilbud tilpasset jeres behov og lokation.",
      en: "Yes, we set up agreements with companies that need regular washing of company cars, vans or entire fleets. Contact us at info@elite-vask.dk for an offer tailored to your needs and location." } },
  { q: { da: "Hvad er jeres aflysningspolitik?", en: "What is your cancellation policy?" },
    a: { da: "Du kan aflyse eller ombooke gratis op til 24 timer inden din booking. Ved aflysning kortere end 24 timer forbeholder vi os retten til at opkræve et aflysningsgebyr på 150 kr. for at dække den reserverede kørselstid.",
      en: "You can cancel or rebook free of charge up to 24 hours before your booking. For cancellations under 24 hours we reserve the right to charge a 150 kr fee to cover the reserved travel time." } },
  { q: { da: "Rengør I sæder af læder og stof forskelligt?", en: "Do you clean leather and fabric seats differently?" },
    a: { da: "Ja. Læder behandles med skånsom rengøring og afsluttes med en fugtighedscreme, der holder læret blødt og forhindrer revner. Stofbeklædning damprenses, hvilket løsner snavs, fjerner lugt og dræber bakterier uden at mætte stoffet med vand.",
      en: "Yes. Leather gets a gentle clean finished with a conditioner that keeps it soft and prevents cracking. Fabric upholstery is steam cleaned, which loosens dirt, removes odours and kills bacteria without soaking the fabric." } },
  { q: { da: "Hvad dækker tilfredshedsgarantien?", en: "What does the satisfaction guarantee cover?" },
    a: { da: "Hvis du ikke er tilfreds med resultatet, kigger vi altid på det igen og udbedrer det, der ikke lever op til vores standard – uden ekstra betaling. Vi beder dig blot kontakte os inden for 24 timer efter vasken med en beskrivelse og evt. billeder.",
      en: "If you're not happy with the result, we always take another look and fix whatever doesn't meet our standard – at no extra cost. We just ask you to contact us within 24 hours of the wash with a description and, ideally, photos." } },
];
