const HTML = `<!-- EKSTRA YDELSER -->
<section class="sec" id="ekstra"><div class="wrap">
  <div class="center"><div class="eyebrow" data-i18n="ex_eyebrow">Tilvalg</div><h2 class="sec-title" data-i18n="ex_title">Ekstra ydelser</h2><p class="sec-sub" data-i18n="ex_sub">Kan tilføjes til enhver pakke. Indgår i Guld pakken.</p></div>
  <div class="ex-grid">
    <div class="ex-item"><div class="ex-ic"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M14 8h4l3 3v4h-2"/><circle cx="7" cy="18" r="2"/><circle cx="17" cy="18" r="2"/><path d="M3 6h8v10H9M5 16H3V6"/></svg></div><div class="ex-tx"><h4 data-i18n="ex1t">Motorrens</h4><p data-i18n="ex1p">Grundig afrensning af motorrum</p></div><span class="ex-pr">400 kr</span></div>
    <div class="ex-item"><div class="ex-ic"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10Z"/></svg></div><div class="ex-tx"><h4 data-i18n="ex2t">Lak- & glansbeskyttelse</h4><p data-i18n="ex2p">Udvendig – langvarig ekstra glans</p></div><span class="ex-pr">300 kr</span></div>
    <div class="ex-item"><div class="ex-ic"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10Z"/><path d="m9 12 2 2 4-4"/></svg></div><div class="ex-tx"><h4 data-i18n="ex3t">Indvendig pleje & beskyttelse</h4><p data-i18n="ex3p">Beskytter og fornyer interiøret</p></div><span class="ex-pr">200 kr</span></div>
    <div class="ex-item"><div class="ex-ic"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="11" cy="4" r="2"/><circle cx="18" cy="8" r="2"/><circle cx="4" cy="8" r="2"/><circle cx="7" cy="14" r="2"/><path d="M14.5 14.5c1 2 1.5 3.5-.5 5-2 1.5-4.5.5-6-1-1.5-1.5-1-4 1-5s4.5 0 5.5 1Z"/></svg></div><div class="ex-tx"><h4 data-i18n="ex4t">Fjernelse af dyrehår</h4><p data-i18n="ex4p">Effektiv fjernelse af hår og fnug</p></div><span class="ex-pr">300–500 kr</span></div>
    <div class="ex-item"><div class="ex-ic"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M5 20v-2a4 4 0 0 1 4-4h2"/><path d="M19 20v-5a3 3 0 0 0-3-3h-1l-2-7H8L6 9"/></svg></div><div class="ex-tx"><h4 data-i18n="ex5t">Sæderens (stof)</h4><p data-i18n="ex5p">Dybderens af stofsæder</p></div><span class="ex-pr">400 kr</span></div>
    <div class="ex-item"><div class="ex-ic"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect x="5" y="9" width="14" height="11" rx="2"/><path d="M8 9V6a4 4 0 0 1 8 0v3"/></svg></div><div class="ex-tx"><h4 data-i18n="ex6t">Rens af barnesæde</h4><p data-i18n="ex6p">Grundig og sikker rengøring</p></div><span class="ex-pr">100 kr</span></div>
  </div>
</div></section>`;
export default function Extras() {
  return <div dangerouslySetInnerHTML={{ __html: HTML }} />;
}
