export const planets = [
  { id:1, name:'Elite Vask', category:'Web Design', color:'#00b4d8', emissive:'#0077b6', size:1.2, orbitRadius:8, orbitSpeed:0.15, url:'https://www.elite-vask.dk', description:'Luxury Car Cleaning Platform', tech:['React','Next.js','AI Booking'], icon:'💎', theme:'ocean' },
  { id:2, name:'Rahweb.dk', category:'Web Agency', color:'#ff6b35', emissive:'#cc4400', size:1.3, orbitRadius:13, orbitSpeed:0.1, url:'https://www.rahweb.dk', description:'Creative Web Design & Development Agency', tech:['Next.js','React','UI/UX'], icon:'🌐', theme:'fire' },
  { id:3, name:'AI Projects', category:'Artificial Intelligence', color:'#7b2d8b', emissive:'#4a0e57', size:1.5, orbitRadius:19, orbitSpeed:0.07, url:'#', description:'Machine Learning & AI Tools', tech:['Python','TensorFlow','OpenAI'], icon:'🤖', theme:'purple' },
  { id:4, name:'E-Commerce', category:'Online Stores', color:'#e63946', emissive:'#9d0208', size:1.0, orbitRadius:25, orbitSpeed:0.05, url:'#', description:'Full-stack E-commerce Platforms', tech:['Next.js','Stripe','MongoDB'], icon:'🛒', theme:'red' },
  { id:5, name:'Mobile Apps', category:'React Native', color:'#2d6a4f', emissive:'#1b4332', size:0.9, orbitRadius:31, orbitSpeed:0.035, url:'#', description:'Cross-platform Mobile Apps', tech:['React Native','Firebase'], icon:'📱', theme:'green' },
  { id:6, name:'Secret Lab', category:'Experiments', color:'#f4a261', emissive:'#e76f51', size:0.7, orbitRadius:37, orbitSpeed:0.025, url:'#', description:'Classified Experiments & R&D', tech:['WebGL','WASM','Rust'], icon:'🔬', theme:'orange' },
  { id:7, name:'Black Hole', category:'Coming Soon', color:'#14213d', emissive:'#000814', size:1.8, orbitRadius:44, orbitSpeed:0.01, url:'#', description:'Something massive is coming...', tech:['???'], icon:'🕳️', theme:'dark' },
]
