export const projects = [
  {
    id: 1,
    title: 'Elite Vask',
    description: 'Modern cleaning service website with booking system',
    color: '#00f5ff',
    url: 'https://elitevask.dk',
    icon: '🧹',
    tech: ['Next.js', 'Vercel', 'Redis'],
  },
  {
    id: 2,
    title: 'Project Alpha',
    description: 'E-commerce platform with custom CMS',
    color: '#ff006e',
    url: '#',
    icon: '🛒',
    tech: ['React', 'Node.js', 'MongoDB'],
  },
  {
    id: 3,
    title: 'Project Beta',
    description: 'SaaS dashboard with real-time analytics',
    color: '#8338ec',
    url: '#',
    icon: '📊',
    tech: ['Next.js', 'Tailwind', 'Supabase'],
  },
  {
    id: 4,
    title: 'Project Gamma',
    description: 'Mobile-first social media app',
    color: '#fb5607',
    url: '#',
    icon: '📱',
    tech: ['React Native', 'Firebase'],
  },
  {
    id: 5,
    title: 'Project Delta',
    description: 'AI-powered content generation tool',
    color: '#06d6a0',
    url: '#',
    icon: '🤖',
    tech: ['Python', 'Next.js', 'OpenAI'],
  },
  {
    id: 6,
    title: 'Project Epsilon',
    description: 'Luxury real estate showcase site',
    color: '#ffd60a',
    url: '#',
    icon: '🏠',
    tech: ['Next.js', 'GSAP', 'Three.js'],
  },
]
